### ISSUE TITLE
(spec text readability) text in table header is unreadable by its color against background

### ISSUE THREAD

**Issue by himorin** [immersive-web/webxr#1245]
We have custom CSS in webxr spec as:
https://github.com/immersive-web/webxr/blob/08e6fab069a60097ab882b75861c9c5168ef4f33/index.bs#L157
``` CSS
  .tg th {
    border-style: solid;
    border-width: 1px;
    background: var(--def-bg);
    color: #fff;
    font-family: sans-serif;
    font-weight: bold;
    border-color: var(--def-border);
  }
```
which results text color `#FFF` (= `#FFFFFF` / white) with background `#def` (= `#DDEEFF` / very light shade of cyan-blue) in normal mode. (background for dark mode is `#080818`)

Bikeshed (and W3C default /TR/ style?) now have color mode switching between bright/dark, so I suppose we should not have non default custom color, or have color for both?

(note, color is defined at only this line in custom CSS of webxr spec)
